version: '2.2'
services:
    jupyter:
        image: jupyter/scipy-notebook
        volumes:
            - ./python_src:/home/jovyan/
        ports:
            - '8888:8888'
        command: start-notebook.sh --ip 0.0.0.0 --NotebookApp.token=''
